// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contable.proto

package com.cg.grpc.contable;

public final class Contable {
  private Contable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cg_grpc_contable_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cg_grpc_contable_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cg_grpc_contable_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cg_grpc_contable_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contable.proto\022\024com.cg.grpc.contable\"\034" +
      "\n\007Request\022\021\n\ttimestamp\030\001 \001(\003\"\027\n\010Response" +
      "\022\013\n\003msg\030\001 \001(\t2\\\n\017ContableService\022I\n\010crea" +
      "tion\022\035.com.cg.grpc.contable.Request\032\036.co" +
      "m.cg.grpc.contable.ResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cg_grpc_contable_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cg_grpc_contable_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cg_grpc_contable_Request_descriptor,
        new java.lang.String[] { "Timestamp", });
    internal_static_com_cg_grpc_contable_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cg_grpc_contable_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cg_grpc_contable_Response_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
