// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contable.proto

package com.cg.grpc.contable;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.contable.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();
}
