// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contable.proto

package com.cg.grpc.contable;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.contable.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
