// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provision.proto

package com.cg.grpc;

public final class Provision {
  private Provision() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cg_grpc_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cg_grpc_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cg_grpc_response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cg_grpc_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017provision.proto\022\013com.cg.grpc\",\n\007reques" +
      "t\022\016\n\006codigo\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\"\027\n\010" +
      "response\022\013\n\003msg\030\001 \001(\t2K\n\020ProvisionServic" +
      "e\0227\n\010creation\022\024.com.cg.grpc.request\032\025.co" +
      "m.cg.grpc.responseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cg_grpc_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cg_grpc_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cg_grpc_request_descriptor,
        new java.lang.String[] { "Codigo", "Timestamp", });
    internal_static_com_cg_grpc_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cg_grpc_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cg_grpc_response_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
