// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provision.proto

package com.cg.grpc;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string codigo = 1;</code>
   */
  java.lang.String getCodigo();
  /**
   * <code>string codigo = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodigoBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
